[package]
name = "tree-sitter-plato"
description = "Plato triple-brace Go template grammar for tree-sitter"
version = "0.19.5"
authors = [
    "Nikita Galaiko <nikita@galaiko.rocks>",
]
keywords = ["incremental", "parsing", "plato"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/ngalaiko/tree-sitter-plato"
edition = "2018"
license = "MIT"

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "0.25"

[build-dependencies]
cc = "1.0"
